### ISSUE TITLE
Pool registered on SMASH server but not showing up in Daedalus

### ISSUE THREAD

**Issue by GiantDole** [input-output-hk/smash#154]
Dear developers,

thank you first of all for your efforts to building this unique decentralized validation system.

A few weeks ago I have successfully registered my Stakepool Augmos with ID 4630cc9a12c0742d779dafb0d0b92fa485481d92a1fbb27fd6f66bf2 on the IOHK SMASH server, as can be seen here:
`https://smash.cardano-mainnet.iohk.io/api/v1/exists/4630cc9a12c0742d779dafb0d0b92fa485481d92a1fbb27fd6f66bf2`

As you can see from [this discussion](https://forum.cardano.org/t/stakepool-not-showing-in-deadalus-possible-errors-checked/50723), I have checked if any errors occurred or if my pool is delisted or retired for some reason. I figured this is not the case. 
I've also ensured to use the right hash by downloading the json from https://git.io/AugmosPool_Meta and using its hash. Additionally, the correct hash shows up in Pooltool. I've also carefully reregistered the pool in order to ensure no errors were made. 

Nevertheless, the pool doesn't show up in Daedalus and looking on SMASH for the metadata doesn't deliver any results as well:
`https://smash.cardano-mainnet.iohk.io/api/v1/metadata/4630cc9a12c0742d779dafb0d0b92fa485481d92a1fbb27fd6f66bf2/0294215f5dd4fc49ff53b8bfe597cb36bf543221c1547d9279c50ce382e743f9`

Right now I'm at a point where I believe to have made no mistakes and have excluded all possible error cases I could research.
That is why I'm finally contacting you and am hoping not to take too much of your precious time: Could you please look into this case, as I've heard that SMASH requires a manual push in some cases?

I appreciate your effort and any further information you can provide!

Thanks a lot,
Adrian

**Comment by ksaric** [comment]
Hi, Adrian.
Sorry for the late reply.

There is no need for any manual push.

I have tested that your hash is correct by using https://docs.cardano.org/projects/smash/en/latest/getting-started/how-to-install-smash.html#how-to-figure-out-the-json-hash (I should probably add some CLI tool for that).

Now, if you check here - https://docs.cardano.org/projects/smash/en/latest/getting-started/how-to-install-smash.html#checking-the-pool-rejection-errors

You will see a bolded info - "This shows all the errors for the pool from a day ago.", which is the default and will be changed to show the last 10 errors since this seems to be confusing.
You can use the format `curl --silent https://smash.cardano-mainnet.iohk.io/api/v1/errors/6b6164af70861c5537cc9c8e50fdae35139ca2c8c6fbb42e8b7e6bfb?fromDate=01.01.2021` to check the errors.

I cannot find any errors regarding your hash `0294215f5dd4fc49ff53b8bfe597cb36bf543221c1547d9279c50ce382e743f9`.

It's not delisted, it's not retired, it's not reserved.

And it doesn't exist.

So I guess we can conclude here that it's not submitted? Can you provide any confirmation that you actually registered/submitted the pool?

Please, do try to submit the pool and observe any errors you might run into. If you do find any output, without exposing your keys, please share them here so I can take a closer look as to what is happening.

In the meantime, I will try to see if there might be some caching issue, but judging from all this info, it's not really probable and the simplest solution, for now, would be that the pool metadata simply wasn't submitted.

**Comment by GiantDole** [comment]
Hello ksaric,

thank you very much for your reply and effort!

I believe the errors from 01.01.2021 are former mistakes I made when playing around with the registration. I suppose the actual errors can be found on 20.03.2021: 
`https://smash.cardano-mainnet.iohk.io/api/v1/errors/4630cc9a12c0742d779dafb0d0b92fa485481d92a1fbb27fd6f66bf2?fromDate=20.03.2021`

It seems as if I haven't inserted the protocol (https) in the URL of the metadata. I've updated this information and submitted the registration once again. With the new hash my metadata finally shows up on the smash server!!!! 
`https://smash.cardano-mainnet.iohk.io/api/v1/metadata/4630cc9a12c0742d779dafb0d0b92fa485481d92a1fbb27fd6f66bf2/687b076e2dbcaccca1a3a49dfea0acb317b488aa941a88ca000f8f3503604b6c`
So grateful that this issue is finally resolved.

Thanks a lot for your efforts! :)
