### ISSUE TITLE
Custom schema

### ISSUE THREAD

**Issue by mbos01** [input-output-hk/smash#155]
I'm trying to run the cexplorer db and the smash db as different schema's in the same db, so it's possible to join data together. As a try-out I first installed the smash db in a smash schema, to see what would happen. Running smash-exe now gives the following error:

smash-exe: SqlError {sqlState = "42P01", sqlExecStatus = FatalError, sqlErrorMsg = "relation \"block\" does not exist", sqlErrorDetail = "", sqlErrorHint = ""}

Apparently the code is looking for a block table in the Public schema, which obviously does not exist. Is this hardcoded? Is it possible to choose another schema?? Are there other ways to work around this?
Cheers!!

**Comment by ksaric** [comment]
Hi, @mbos01.
Sorry for the late reply, but that is exactly what I was working on and we are very close to having them both working together, but not on the same schema.
There are several issues with using a single schema for both:
- migration issues (`db-sync` usually wipes all the data clean every upgrade, `smash` cannot do that since it contains some delisted pools and reserved tickers)
- table collisions - the names of some of tables are the same and there is a fundamental reason for that - they use the same mechanism for upgrade, for example
- the schemas must then be a product of both `smash` and `db-sync` - we would then have to maintain both schemas in sync which is bothersome, at least, if not a really big pain point, since it would require syncing both products

You could try to create your queries by selecting both schemas - https://stackoverflow.com/questions/1463849/querying-across-schemas-in-postgres

Or wait until we have the executable that will run both and enable `smash` to use it's HTTP API which would allow you to query using a local HTTP client using JSON.

**Comment by mbos01** [comment]
Hi Ksaric, no problem at all! Appreciate the hard work!

Thanks for the update, really great stuff, have a great day
